name: Tests

on:
    workflow_dispatch:   # this is unique for external triggering by another repo
    push:
        branches:        # Run tests when commits are pushed to these branches in your repo
            - main
            - master
            - develop
            - dev/*
    pull_request:        # Run tests when pull requests are made on these branches in your repo
        branches:
            - main
            - master
            - develop
            - dev/*

jobs:
    call-tests:
        name: Extension tests
        uses: iMattPro/test-framework/.github/workflows/tests.yml@updates
        with:
            EXTNAME: acme/demo   # Your extension vendor/package name
