name: Tests

on:
    workflow_dispatch:   # this is unique for external triggering by another repo
    push:
    pull_request:        # Run tests when pull requests are made on these branches in your repo

jobs:
    call-tests:
        name: Extension tests
        uses: iMattPro/test-framework/.github/workflows/tests.yml@checktests
        with:
            EXTNAME: acme/demo   # Your extension vendor/package name
